#!/bin/bash

RELEASES=$(curl -qsL https://api.github.com/repos/nginxinc/docker-nginx/tags | grep \"name\" | sed 's/[^ ]*m[^ ]*//g' | sed 's/\(.*\),/\1 /' | sed 's/^[ \t]*//;s/[ \t]*$//' | sed 's/"//g')
DOCKER_REPO="openbridge/nginx"
IMG=$(basename $DOCKER_REPO)
for tag in ${RELEASES}; do
    echo "============== Building ${IMG}:$tag"
    docker build --build-arg NGINX_VERSION=$tag -t ${DOCKER_REPO}:$tag .
done
latest=$(echo ${RELEASES}|cut -d" " -f1)
echo "============== Building ${IMG}:latest"
docker build --build-arg NGINX_VERSION=$latest -t ${DOCKER_REPO}:latest .

exit 0
