#!/bin/bash

GITHUB_REPO="nginxinc/docker-nginx"
RELEASES=$(curl -qsL https://api.github.com/repos/nginxinc/docker-nginx/tags | grep \"name\"| sed "s/^ *\"name\" *: *\"\(\([0-9]\+\.\)\+[0-9]\+\\)\" *,/\1/g")
DOCKER_REPO="openbridge/nginx"
IMG=$(basename $DOCKER_REPO)
for tag in ${RELEASES}; do
    echo "============== Pushing ${IMG}:$tag"
    docker push ${DOCKER_REPO}:$tag
done
echo "============== Pushing ${IMG}:latest"
docker push ${DOCKER_REPO}:latest

exit 0
